#include <pspkernel.h>
#include <pspdebug.h>
#include <pspctrl.h>
#include <pspiofilemgr.h>
#include <stdio.h>
#include <string.h>

#include "rc_client.h"
#include "ra_rc_bridge.h"

PSP_MODULE_INFO("RA-PSP Login", PSP_MODULE_USER, 0, 9);
PSP_MAIN_THREAD_ATTR(THREAD_ATTR_USER);

#define LOGIN_PATH "ms0:/SEPLUGINS/RA-PSP/login.ini"
#define AUTH_PATH  "ms0:/SEPLUGINS/RA-PSP/auth.ini"

static volatile int g_done = 0;
static volatile int g_ok = 0;
static char g_username[64];
static char g_password[128];
static char g_hash[40];

static void trim(char* s) {
    size_t n;
    if (!s) return;
    while (*s == ' ' || *s == '\t') memmove(s, s + 1, strlen(s));
    n = strlen(s);
    while (n && (s[n-1]=='\r' || s[n-1]=='\n' || s[n-1]==' ' || s[n-1]=='\t')) s[--n] = 0;
}

static int load_login_ini(void) {
    SceUID fd;
    char buf[1024];
    int n;
    char* line;
    memset(g_username, 0, sizeof(g_username));
    memset(g_password, 0, sizeof(g_password));
    memset(g_hash, 0, sizeof(g_hash));

    fd = sceIoOpen(LOGIN_PATH, PSP_O_RDONLY, 0);
    if (fd < 0) return -1;
    n = sceIoRead(fd, buf, sizeof(buf) - 1);
    sceIoClose(fd);
    if (n <= 0) return -2;
    buf[n] = 0;

    line = strtok(buf, "\n");
    while (line) {
        char* eq = strchr(line, '=');
        if (eq) {
            *eq = 0;
            trim(line);
            trim(eq + 1);
            if (strcmp(line, "username") == 0) snprintf(g_username, sizeof(g_username), "%s", eq + 1);
            else if (strcmp(line, "password") == 0) snprintf(g_password, sizeof(g_password), "%s", eq + 1);
            else if (strcmp(line, "game_hash") == 0) snprintf(g_hash, sizeof(g_hash), "%s", eq + 1);
        }
        line = strtok(NULL, "\n");
    }

    return (g_username[0] && g_password[0] && strlen(g_hash) == 32) ? 0 : -3;
}

static int save_auth_ini(void) {
    rc_client_t* client = ra_rc_client();
    const rc_client_user_t* user = client ? rc_client_get_user_info(client) : NULL;
    char out[512];
    int len;
    SceUID fd;
    if (!user || !user->username || !user->token || !user->token[0]) return -1;

    sceIoMkdir("ms0:/SEPLUGINS/RA-PSP", 0777);
    len = snprintf(out, sizeof(out),
        "# Generated by RA-PSP Login. Do not share this file.\n"
        "username=%s\n"
        "token=%s\n"
        "game_hash=%s\n",
        user->username, user->token, g_hash);
    if (len <= 0 || len >= (int)sizeof(out)) return -2;

    fd = sceIoOpen(AUTH_PATH, PSP_O_CREAT | PSP_O_TRUNC | PSP_O_WRONLY, 0600);
    if (fd < 0) return -3;
    sceIoWrite(fd, out, (SceSize)len);
    sceIoClose(fd);
    return 0;
}

static void on_event(const ra_ui_event_t* event, void* userdata) {
    (void)userdata;
    if (!event) return;
    if (event->type == RA_UI_EVENT_LOGIN_OK) {
        g_ok = (save_auth_ini() == 0);
        g_done = 1;
    } else if (event->type == RA_UI_EVENT_LOGIN_FAILED) {
        g_ok = 0;
        g_done = 1;
    }
}

int main(int argc, char** argv) {
    SceCtrlData pad;
    int rc;
    (void)argc; (void)argv;

    pspDebugScreenInit();
    sceCtrlSetSamplingCycle(0);
    sceCtrlSetSamplingMode(PSP_CTRL_MODE_DIGITAL);

    pspDebugScreenPrintf("RA-PSP LOGIN v0.9.1\n\n");
    pspDebugScreenPrintf("First-time authentication only.\n");
    pspDebugScreenPrintf("Reading: %s\n\n", LOGIN_PATH);

    rc = load_login_ini();
    if (rc < 0) {
        pspDebugScreenPrintf("ERROR: login.ini missing or incomplete (%d).\n", rc);
        pspDebugScreenPrintf("Need username, password and 32-char game_hash.\n");
        goto exit_wait;
    }

    if (ra_rc_init(on_event, NULL) < 0) {
        pspDebugScreenPrintf("ERROR: could not initialize rc_client.\n");
        goto exit_wait;
    }

    pspDebugScreenPrintf("Connecting PSP Wi-Fi profile 1...\n");
    pspDebugScreenPrintf("Logging in as %s...\n", g_username);
    rc = ra_rc_login_with_password(g_username, g_password);
    memset(g_password, 0, sizeof(g_password));
    if (rc < 0) {
        pspDebugScreenPrintf("ERROR: login request could not start (%d).\n", rc);
        ra_rc_shutdown();
        goto exit_wait;
    }

    while (!g_done) {
        ra_rc_do_frame();
        sceKernelDelayThread(16666);
    }

    if (g_ok) {
        pspDebugScreenPrintf("\nSUCCESS. auth.ini was created.\n");
        pspDebugScreenPrintf("Delete login.ini now. The password is no longer needed.\n");
        pspDebugScreenPrintf("Then install/enable ra_psp_ingame.prx.\n");
    } else {
        pspDebugScreenPrintf("\nLOGIN FAILED. Check Wi-Fi/profile/credentials.\n");
    }
    ra_rc_shutdown();

exit_wait:
    pspDebugScreenPrintf("\nPress O to exit.\n");
    for (;;) {
        sceCtrlReadBufferPositive(&pad, 1);
        if (pad.Buttons & PSP_CTRL_CIRCLE) break;
        sceKernelDelayThread(20000);
    }
    sceKernelExitGame();
    return 0;
}
